- name: Set up Rust
  uses: actions/setup-rust@v2
  with:
    rust-version: stable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions/setup-rust@v2  # Updated to v2
      with:
        rust-version: stable

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install

    - name: Install DFX
      run: |
        curl -o /tmp/dfx.tar.gz https://github.com/dfinity/sdk/releases/download/0.17.0/dfx-x86_64-linux-0.17.0.tar.gz
        tar -xvzf /tmp/dfx.tar.gz -C /tmp/
        sudo mv /tmp/dfx /usr/local/bin/

    - name: Start local replica (dfx start)
      run: |
        nohup dfx start --background
        # Wait a few seconds to ensure that dfx has started
        sleep 5

    - name: Generate .did IDL file
      run: npm run gen-deploy

    - name: Run tests
      run: cargo test  # Assuming you are using cargo to run your Rust tests

    - name: Stop dfx
      run: |
        dfx stop
